name: all_animations
repository: https://github.com/shirvanie/all_animations/tree/master/
issue_tracker: https://github.com/shirvanie/all_animations/issues
homepage: https://github.com/shirvanie/all_animations
description: All Animations
email: ihamedshirvani@gmail.com
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
